# Generated by Django 2.2.2 on 2019-09-19 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('date_send', models.DateField(default=datetime.date.today, verbose_name='Data do Envio')),
                ('email_send', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('subject_send', models.CharField(max_length=100, verbose_name='Assunto')),
                ('message_send', models.TextField(verbose_name='Mensagem')),
                ('copy_send', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mails',
                'ordering': ['date_send'],
            },
        ),
    ]
