# Generated by Django 2.2.2 on 2019-09-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_site', '0002_auto_20190924_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject_send',
            field=models.CharField(choices=[('Elogio', 'Elogio'), ('Diverso', 'Diverso'), ('Dúvidas', 'Dúvidas'), ('Reclamação', 'Reclamação')], default='Escolha uma opção', max_length=100, verbose_name='Assunto*'),
        ),
    ]
