# Generated by Django 2.2.2 on 2019-09-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_site', '0003_auto_20190925_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject_send',
            field=models.CharField(choices=[('Elogio(s)', 'Elogio(s)'), ('Diverso(s)', 'Diverso(s)'), ('Dúvida(s)', 'Dúvida(s)'), ('Reclamação(s)', 'Reclamação(s)')], max_length=100, verbose_name='Assunto*'),
        ),
    ]
