# Generated by Django 2.2.2 on 2019-09-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_site', '0004_auto_20190925_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject_send',
            field=models.CharField(choices=[('Elogio', 'Elogio'), ('Diverso', 'Diverso'), ('Dúvida', 'Dúvida'), ('Reclamação', 'Reclamação')], max_length=100, verbose_name='Assunto*'),
        ),
    ]
