# Generated by Django 2.2.2 on 2019-09-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_site', '0005_auto_20190925_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_send'], 'verbose_name': 'E-mail de contato', 'verbose_name_plural': 'E-mails dos contatos'},
        ),
        migrations.AddField(
            model_name='contact',
            name='returns_send',
            field=models.BooleanField(default=True, verbose_name='E-mail retornado?'),
        ),
    ]
