# Generated by Django 2.2.2 on 2019-09-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_site', '0006_auto_20190925_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='returns_send',
            new_name='return_send',
        ),
    ]
