# Generated by Django 2.2.2 on 2019-09-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_site', '0007_auto_20190925_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_send'], 'verbose_name': 'E-mail de contato', 'verbose_name_plural': 'E-mails de contatos'},
        ),
        migrations.AddField(
            model_name='contact',
            name='message_return',
            field=models.TextField(default='', verbose_name='Resposta*'),
        ),
    ]
