# Generated by Django 2.2.2 on 2019-09-26 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_site', '0011_contact_date_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_update',
        ),
    ]
