# Generated by Django 2.2.2 on 2019-08-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='qnow_user_user',
        ),
    ]
