# Generated by Django 2.2.2 on 2019-08-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0002_auto_20190802_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome e Sobrenome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(default='', max_length=200, verbose_name='Rua'),
        ),
    ]
