# Generated by Django 2.2.2 on 2019-08-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0003_auto_20190830_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
