# Generated by Django 2.2.2 on 2019-08-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Rua'),
        ),
    ]
