# Generated by Django 2.2.2 on 2019-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0009_auto_20190831_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(default='Indefinido', max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Indefinido', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='Indefinido', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(default='Indefinido', max_length=200, verbose_name='Rua'),
        ),
    ]
