# Generated by Django 2.2.2 on 2019-09-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0010_auto_20190913_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='Indefinido', max_length=10, verbose_name='Classificação'),
        ),
    ]
