# Generated by Django 2.2.2 on 2020-01-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0011_auto_20190913_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Mov/Autorizada'),
        ),
    ]
