# Generated by Django 2.2.2 on 2020-01-23 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0014_auto_20200123_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_accepted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Contrato(S/N'),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_date_accepted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
