# Generated by Django 2.2.2 on 2020-02-11 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0015_auto_20200123_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contract_accepted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Li e concordo(S/N)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contract_date_accepted',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Li e concordei em:'),
        ),
    ]
