# Generated by Django 2.2.2 on 2020-03-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0016_auto_20200211_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(default='Indefinido', max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
