# Generated by Django 2.2.2 on 2020-03-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0017_auto_20200304_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='delivery_time',
            field=models.CharField(default='', max_length=30, verbose_name='Prazo de Entrega Padrão'),
        ),
        migrations.AddField(
            model_name='user',
            name='form_payment',
            field=models.CharField(default='', max_length=50, verbose_name='Forma de Pagamento Padrão'),
        ),
        migrations.AlterField(
            model_name='user',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Desativar Movimentação'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Acessar o Sistema(S/N)'),
        ),
    ]
