# Generated by Django 2.2.2 on 2020-03-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0018_auto_20200327_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Inicio das Atividades'),
        ),
        migrations.AlterField(
            model_name='user',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Prazo de Entrega Padrão'),
        ),
        migrations.AlterField(
            model_name='user',
            name='form_payment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento Padrão'),
        ),
    ]
