# Generated by Django 2.2.2 on 2020-03-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0019_auto_20200327_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='information',
            field=models.TextField(blank=True, verbose_name='Informações oa Cliente'),
        ),
        migrations.AlterField(
            model_name='user',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Prazo de Entrega - Padrão'),
        ),
        migrations.AlterField(
            model_name='user',
            name='form_payment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento - Padrão'),
        ),
    ]
