# Generated by Django 2.2.2 on 2020-05-04 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0021_auto_20200331_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contract_date_accepted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Li e concordei em:'),
        ),
    ]
