# Generated by Django 2.2.2 on 2020-05-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_user', '0022_auto_20200504_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='information',
            field=models.TextField(blank=True, max_length=500, verbose_name='Conquistando o Cliente'),
        ),
    ]
