# Generated by Django 2.2.2 on 2019-10-29 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default=datetime.date.today)),
                ('date_validate', models.DateField(blank=True, null=True)),
                ('quotation_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('delivery_time', models.CharField(default='', max_length=30)),
                ('form_payment', models.CharField(default='', max_length=50)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
                'ordering': ['date_create'],
            },
        ),
    ]
