# Generated by Django 2.2.2 on 2019-10-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuotationPrice',
        ),
    ]
