# Generated by Django 2.2.2 on 2019-11-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0004_auto_20191029_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='quotation_value',
            field=models.FloatField(default=0, verbose_name='Valor da Cotação'),
        ),
    ]
