# Generated by Django 2.2.2 on 2019-11-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0005_auto_20191101_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='quotation_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da Cotação'),
        ),
    ]
