# Generated by Django 2.2.2 on 2019-11-01 14:59

from django.db import migrations, models
import qnow_provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0007_auto_20191101_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='quotation_value',
            field=models.FloatField(validators=[qnow_provider.models.validate_decimals]),
        ),
    ]
