# Generated by Django 2.2.2 on 2019-11-04 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0036_delete_quotationprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnow_provider', '0013_auto_20191101_1744'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotationprice',
            unique_together={('quotation_number', 'quotation_provider')},
        ),
    ]
