# Generated by Django 2.2.2 on 2019-11-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0014_auto_20191104_0940'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotationprice',
            unique_together=set(),
        ),
    ]
