# Generated by Django 2.2.2 on 2019-11-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0016_auto_20191104_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationprice',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado?'),
        ),
    ]
