# Generated by Django 2.2.2 on 2020-03-05 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0017_quotationprice_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationprice',
            options={'ordering': ['quotation_number'], 'verbose_name': 'Preço', 'verbose_name_plural': 'Preços'},
        ),
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.date.today, verbose_name='Validade da Cotação'),
        ),
    ]
