# Generated by Django 2.2.2 on 2020-03-11 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0018_auto_20200304_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_create',
            field=models.DateField(default=datetime.date.today, verbose_name='Data da Orçamento'),
        ),
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 3, 20, 23, 11, 16, 415034), verbose_name='Validade da Cotação'),
        ),
    ]
