# Generated by Django 2.2.2 on 2020-03-11 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0035_auto_20200310_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 3, 20, 23, 57, 7, 330876), verbose_name='Validade da Cotação'),
        ),
    ]
