# Generated by Django 2.2.2 on 2020-03-11 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0037_auto_20200310_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 3, 21, 0, 0, 20, 576708), verbose_name='Validade da Cotação'),
        ),
    ]
