# Generated by Django 2.2.2 on 2020-03-11 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0038_auto_20200311_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 3, 21, 0, 10, 26, 31127), verbose_name='Validade da Cotação'),
        ),
    ]
