# Generated by Django 2.2.2 on 2020-03-13 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0039_auto_20200311_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 16, 43, 1, 834528), verbose_name='Validade da Cotação'),
        ),
    ]
