# Generated by Django 2.2.2 on 2020-03-13 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0040_auto_20200313_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 16, 45, 23, 378541), verbose_name='Validade da Cotação'),
        ),
    ]
