# Generated by Django 2.2.2 on 2020-03-17 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0041_auto_20200313_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 21, 0, 47, 84882), verbose_name='Validade da Cotação'),
        ),
    ]
