# Generated by Django 2.2.2 on 2020-03-22 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0042_auto_20200316_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 1, 20, 35, 25, 500358), verbose_name='Validade da Cotação'),
        ),
    ]
