# Generated by Django 2.2.2 on 2020-03-24 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0045_auto_20200323_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationprice',
            name='commission_paid',
            field=models.BooleanField(default=False, verbose_name='Comissão(Paga?)'),
        ),
        migrations.AddField(
            model_name='quotationprice',
            name='commission_paid_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Comissão(Data)'),
        ),
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 2, 22, 5, 11, 870015), verbose_name='Validade da Cotação'),
        ),
    ]
