# Generated by Django 2.2.2 on 2020-03-25 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0046_auto_20200323_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationprice',
            name='approved_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Aprovação(Data)'),
        ),
        migrations.AlterField(
            model_name='quotationprice',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado(S/N)'),
        ),
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 4, 11, 37, 55, 952313), verbose_name='Validade da Cotação'),
        ),
    ]
