# Generated by Django 2.2.2 on 2020-03-28 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0047_auto_20200325_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Aprovação(Data)'),
        ),
        migrations.AlterField(
            model_name='quotationprice',
            name='commission_paid',
            field=models.BooleanField(default=False, verbose_name='Comissão(Paga S/N)'),
        ),
        migrations.AlterField(
            model_name='quotationprice',
            name='commission_paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Comissão(Previsão p/Pagto)'),
        ),
        migrations.AlterField(
            model_name='quotationprice',
            name='date_create',
            field=models.DateField(default=datetime.date.today, verbose_name='Data do Orçamento'),
        ),
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 50, 23, 690321), verbose_name='Validade da Cotação'),
        ),
    ]
