# Generated by Django 2.2.2 on 2020-03-31 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0049_auto_20200327_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 37, 39, 372386), verbose_name='Validade da Cotação'),
        ),
    ]
