# Generated by Django 2.2.2 on 2020-03-31 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0050_auto_20200330_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 11, 1, 49, 915329), verbose_name='Validade da Cotação'),
        ),
    ]
