# Generated by Django 2.2.2 on 2020-05-12 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_provider', '0054_auto_20200512_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 5, 22, 15, 36, 23, 71229), verbose_name='Validade da Cotação'),
        ),
    ]
