# Generated by Django 2.2.2 on 2019-07-31 11:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qnow_client.models
import qnow_user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Móvel',
                'verbose_name_plural': 'Tipo de Móveis',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_create', models.DateField(default=datetime.date.today)),
                ('date_update', models.DateField(default=datetime.date.today)),
                ('house_type', models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Comercial', 'Comercial'), ('Escritório', 'Escritório'), ('Outro', 'Outro')], default='Casa', help_text='Nos informe o tipo do seu imóvel(Apartamento, casa...)', max_length=20, verbose_name='Tipo de imóvel para cotação?')),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Em Análise'), (2, 'Liberado'), (3, 'Orçado')], default=0)),
                ('house_set', models.CharField(default='Digite aqui!', max_length=100)),
                ('mobile_description', models.CharField(default='Encontrei na lista acima!', max_length=100)),
                ('particulars', models.TextField()),
                ('image_environment', models.FileField(blank=True, upload_to=qnow_client.models.user_directory_path, validators=[qnow_client.models.validate_file_extension])),
                ('image_project', models.FileField(blank=True, upload_to=qnow_client.models.user_directory_path, validators=[qnow_client.models.validate_file_extension])),
                ('client', models.ForeignKey(default=qnow_user.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to=settings.AUTH_USER_MODEL)),
                ('mobile_type', models.ForeignKey(on_delete=True, related_name='MobileType', to='qnow_client.MobilieType')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['mobile_type'],
            },
        ),
    ]
