# Generated by Django 2.2.2 on 2019-08-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0002_quotation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
