# Generated by Django 2.2.2 on 2019-08-13 20:33

from django.db import migrations, models
import qnow_client.models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0003_auto_20190808_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='image_environment',
            field=models.FileField(blank=True, null=True, upload_to=qnow_client.models.user_directory_path, validators=[qnow_client.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='image_project',
            field=models.FileField(blank=True, null=True, upload_to=qnow_client.models.user_directory_path, validators=[qnow_client.models.validate_file_extension]),
        ),
    ]
