# Generated by Django 2.2.2 on 2019-08-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0005_auto_20190815_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Em Análise'), (2, 'Liberado'), (3, 'Orçado'), (4, 'Finalizado'), (5, 'Cancelado'), (6, 'Destativado')], default=0),
        ),
    ]
