# Generated by Django 2.2.2 on 2019-08-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0006_auto_20190815_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estágio da Cotação',
                'verbose_name_plural': 'Estágios da Cotação',
                'ordering': ['description'],
            },
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='status',
        ),
        migrations.AddField(
            model_name='quotation',
            name='stage',
            field=models.ForeignKey(default=0, on_delete=True, related_name='QuotationStage', to='qnow_client.QuotationStage'),
        ),
    ]
