# Generated by Django 2.2.2 on 2019-08-20 13:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0011_auto_20190816_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='image_environment',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='image_project',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
