# Generated by Django 2.2.2 on 2019-08-20 14:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0012_auto_20190820_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='image_environment',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='image_project',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
