# Generated by Django 2.2.2 on 2019-08-20 19:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0016_auto_20190820_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='image_environment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_environment'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='image_project',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_project'),
        ),
    ]
