# Generated by Django 2.2.2 on 2019-08-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0017_auto_20190820_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['stage_id', 'date_create', 'id'], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
    ]
