# Generated by Django 2.2.2 on 2019-08-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0019_quotationstage_explication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationstage',
            options={'ordering': ['status'], 'verbose_name': 'Estágio da Cotação', 'verbose_name_plural': 'Estágios da Cotação'},
        ),
        migrations.AlterField(
            model_name='quotation',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=True, related_name='quotation_stage', to='qnow_client.QuotationStage'),
        ),
    ]
