# Generated by Django 2.2.2 on 2019-08-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0020_auto_20190827_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=True, related_name='QuotationStage', to='qnow_client.QuotationStage'),
        ),
    ]
