# Generated by Django 2.2.2 on 2019-08-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0021_auto_20190827_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-id'], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
        migrations.AlterField(
            model_name='quotation',
            name='house_set',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
