# Generated by Django 2.2.2 on 2019-08-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0024_auto_20190830_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='house_type',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Comercial', 'Comercial'), ('Escritório', 'Escritório'), ('Outro', 'Outro')], default='Casa', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='mobile_description',
            field=models.CharField(blank=True, default='Encontrei na lista acima!', max_length=100),
        ),
    ]
