# Generated by Django 2.2.2 on 2019-09-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0026_quotation_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
    ]
