# Generated by Django 2.2.2 on 2019-09-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0027_auto_20190911_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationstage',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='quotationstage',
            name='explication',
            field=models.CharField(default='Aguardando texto...', max_length=200, verbose_name='Descrição da Situação'),
        ),
    ]
