# Generated by Django 2.2.2 on 2019-09-16 17:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0028_auto_20190913_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='house_type',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Comercial', 'Comercial'), ('Escritório', 'Escritório'), ('Outro', 'Outro')], default='Casa', max_length=20, verbose_name='Tipo Imóvel'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='image_environment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='image_project',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='mobile_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
