# Generated by Django 2.2.2 on 2019-10-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0029_auto_20190916_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.ForeignKey(on_delete=True, related_name='quotation_price', to='qnow_client.Quotation')),
            ],
        ),
    ]
