# Generated by Django 2.2.2 on 2019-10-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0030_quotationprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationprice',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
