# Generated by Django 2.2.2 on 2019-10-25 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0031_quotationprice_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationprice',
            options={'verbose_name': 'Preço', 'verbose_name_plural': 'Preços'},
        ),
        migrations.AddField(
            model_name='quotationprice',
            name='date_create',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='quotationprice',
            name='delivery_time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quotationprice',
            name='form_payment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quotationprice',
            name='quotation_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
