# Generated by Django 2.2.2 on 2019-10-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0032_auto_20191025_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationprice',
            name='date_validate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
