# Generated by Django 2.2.2 on 2019-10-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0033_auto_20191025_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationprice',
            options={'ordering': ['quotation_number', 'date_create'], 'verbose_name': 'Preço', 'verbose_name_plural': 'Preços'},
        ),
    ]
