# Generated by Django 2.2.2 on 2019-10-29 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnow_client', '0034_auto_20191025_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationprice',
            name='quotation_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
