# Generated by Django 2.2.2 on 2019-10-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0035_quotationprice_quotation_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuotationPrice',
        ),
    ]
