# Generated by Django 2.2.2 on 2020-03-05 01:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnow_client', '0036_delete_quotationprice'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='quotation',
            index_together={('client',)},
        ),
    ]
