# Generated by Django 2.2.2 on 2020-03-05 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0040_auto_20200304_2246'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='quotation',
            index_together=set(),
        ),
    ]
