# Generated by Django 2.2.2 on 2020-03-11 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0041_auto_20200304_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 23, 23, 42, 746105), verbose_name='Validade da Cotação'),
        ),
    ]
