# Generated by Django 2.2.2 on 2020-03-11 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0043_auto_20200310_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 23, 29, 44, 154434), verbose_name='Validade da Cotação'),
        ),
    ]
