# Generated by Django 2.2.2 on 2020-03-11 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0045_auto_20200310_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_create',
            field=models.DateField(default=datetime.date.today, verbose_name='Emissão'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 23, 48, 58, 17773), verbose_name='Validade'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='mobile_type',
            field=models.ForeignKey(on_delete=True, related_name='MobileType', to='qnow_client.MobilieType', verbose_name='Móvel'),
        ),
    ]
