# Generated by Django 2.2.2 on 2020-03-11 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0046_auto_20200310_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 23, 50, 49, 583113), verbose_name='Validade'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='mobile_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Móvel Complementar'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=True, related_name='QuotationStage', to='qnow_client.QuotationStage', verbose_name='Estágio'),
        ),
    ]
