# Generated by Django 2.2.2 on 2020-03-11 02:54

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0047_auto_20200310_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 23, 54, 0, 599994), verbose_name='Validade'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='image_environment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem-1'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='image_project',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem-2'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='particulars',
            field=models.TextField(verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='removed',
            field=models.BooleanField(default=False, verbose_name='Removida'),
        ),
    ]
