# Generated by Django 2.2.2 on 2020-03-11 02:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qnow_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0048_auto_20200310_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 23, 54, 31, 309377), verbose_name='Validade'),
        ),
    ]
