# Generated by Django 2.2.2 on 2020-03-11 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0052_auto_20200311_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 0, 10, 23, 878628), verbose_name='Validade(Data)'),
        ),
    ]
