# Generated by Django 2.2.2 on 2020-03-17 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0055_auto_20200313_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 21, 0, 44, 957859), verbose_name='Validade(Data)'),
        ),
    ]
