# Generated by Django 2.2.2 on 2020-03-22 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0056_auto_20200316_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 20, 35, 23, 555346), verbose_name='Validade(Data)'),
        ),
    ]
