# Generated by Django 2.2.2 on 2020-03-24 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0057_auto_20200322_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 7, 21, 5, 3, 10951), verbose_name='Validade(Data)'),
        ),
    ]
