# Generated by Django 2.2.2 on 2020-03-24 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0064_auto_20200323_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 7, 21, 24, 27, 11361), verbose_name='Validade(Data)'),
        ),
    ]
