# Generated by Django 2.2.2 on 2020-03-24 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0071_auto_20200323_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 7, 22, 5, 9, 761476), verbose_name='Validade(Data)'),
        ),
    ]
