# Generated by Django 2.2.2 on 2020-03-28 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0073_auto_20200325_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 21, 50, 21, 808320), verbose_name='Validade(Data)'),
        ),
    ]
