# Generated by Django 2.2.2 on 2020-03-28 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0074_auto_20200327_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 22, 14, 9, 576237), verbose_name='Validade(Data)'),
        ),
    ]
