# Generated by Django 2.2.2 on 2020-03-31 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0075_auto_20200327_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 4, 14, 21, 37, 37, 442046), verbose_name='Validade(Data)'),
        ),
    ]
