# Generated by Django 2.2.2 on 2020-05-04 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0077_auto_20200331_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 9, 44, 36, 454794), verbose_name='Validade(Data)'),
        ),
    ]
