# Generated by Django 2.2.2 on 2020-05-12 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0079_auto_20200512_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 5, 27, 15, 15, 27, 124832), verbose_name='Validade(Data)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='view_environment_quotation_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar Foto Imagem-1 na Home'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='view_project_quotation_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar Foto Imagem-2 na Home'),
        ),
    ]
