# Generated by Django 2.2.2 on 2020-05-12 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnow_client', '0080_auto_20200512_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_validate',
            field=models.DateField(default=datetime.datetime(2020, 5, 27, 15, 36, 20, 512064), verbose_name='Validade(Data)'),
        ),
    ]
